adding qtum connector
tatumio/tatum-blockchain-connector pull request #29
Opened 2021-07-07 06:40 UTC by Rachit-gaur

2021-07-07 07:25 UTC, samuelsramko requested changes

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/package.json
> +    "@tatumio/tatum": "^1.14.5",
increase tatumjs lib peer dependency version to the latest one

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    @Post('v3/qtum/contractCall')
please unify paths according to other blockchain integrations

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    @Post('v3/qtum/sendRawTx')
please unify paths according to other blockchain integrations

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +            return await this.service.contractCall(body.testnet, body.address, body.encodedData);
testnet is never a parameter inside the request. It is obtained from the API key

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    async contractCall(@Body() body: contractCall) {
contractCall should start with capital C

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    @Get('/v3/qtum/:chain/utxos/:address')
chain != testnet. should be ommited

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    @Get('/v3/qtum/:chain/:address/info')
unify path with other account detail endpoints

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    @Get('/v3/qtum/:chain/transactions/:id/:pageNum')
use common Pagination.ts with pageSize and offset

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    @Get('/v3/qtum/:chain/transactions/:id/:pageNum')
what is id parameter here?

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumEndpointGuard.ts
> +export class QtumEndpointGuard implements CanActivate {
this guard does not have to be here. It's not like Quorum or Hyperledger, where everyone could have its own instance of private nodes. Please delete this.

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/QtumService.ts
> +            const res = await axios.get(baseURL +
we should do this contrctCall more easier for devs. They don't know how to create encoded data etc. Please take a look on how we do it in ETH or BSC - InvokeSmartContractMethod.

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/dto/qtumTx.ts
> +export class QtumIRawTransactionInfo {
these classes / interfaces should be split into separate files

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/index.ts
> +export const QTUM_HEADER_ENDPOINT = 'x-qtum-endpoint';
not necessary

2021-07-07 07:25 UTC, samuelsramko commented on qtum-connector/module/src/index.ts
> +export const INSIGHT_BASEURLS: { [key: string]: string } = {
renme to sthing more clear, like QTUM_URLS.

2021-07-16 06:48 UTC, samuelsramko requested changes

2021-07-16 06:48 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    async getInfo(@Param() address: string) {
rename oath to v3/qtum/address/:address/balance

2021-07-16 06:48 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    async getQtumTransactions(@Param() path: { address: string, pageNum: number }): Promise<QtumIRawTransactions> {
pagination should be done in a unified way. We have query parameter pageSize and offset in Pagination.ts file. Please use this aproach.

2021-07-16 06:48 UTC, samuelsramko commented on qtum-connector/module/src/QtumService.ts
> +    public async getBlock(hash: string): Promise<QtumBlock> {
this method should cover get block by hash and get block by height. Is this supported now?

2021-07-16 06:48 UTC, samuelsramko commented on qtum-connector/module/src/QtumService.ts
> +            const baseURL = network ? QTUM_URLS['QTUM_TESTNET'] : QTUM_URLS['QTUM_MAINNET']
url should be obtained from getFirstNodeUrl()

2021-07-16 06:48 UTC, samuelsramko commented on qtum-connector/module/src/QtumService.ts
> +            const baseURL = network ? QTUM_URLS['QTUM_TESTNET'] : QTUM_URLS['QTUM_MAINNET']
url should be obtained from getFirstNodeUrl()

2021-07-16 06:48 UTC, samuelsramko commented on qtum-connector/module/src/QtumService.ts
> +            const baseURL = network ? QTUM_URLS['QTUM_TESTNET'] : QTUM_URLS['QTUM_MAINNET']
url should be obtained from getFirstNodeUrl()

2021-07-16 06:48 UTC, samuelsramko commented on qtum-connector/module/src/QtumService.ts
> +            const baseURL = network ? QTUM_URLS['QTUM_TESTNET'] : QTUM_URLS['QTUM_MAINNET']
url should be obtained from getFirstNodeUrl()

2021-07-16 07:20 UTC, Rachit-gaur commented on qtum-connector/module/src/QtumService.ts
> +    public async getBlock(hash: string): Promise<QtumBlock> {
get block by hash is covered, and getCurrentBlock will give the hash of latest block.
for only these 2 functions I have used the node that we have hosted for qtum

2021-07-16 07:21 UTC, Rachit-gaur commented on qtum-connector/module/src/QtumService.ts
> +            const baseURL = network ? QTUM_URLS['QTUM_TESTNET'] : QTUM_URLS['QTUM_MAINNET']
actually this is not from the node but we are consuming the insight api to fetch these details, getFirstNodeUrl() will be used to fetch nodes, do I enter all these urls there itself?

2021-07-16 07:24 UTC, Rachit-gaur commented on qtum-connector/module/src/QtumService.ts
> +            const baseURL = network ? QTUM_URLS['QTUM_TESTNET'] : QTUM_URLS['QTUM_MAINNET']
shall I make all the calls from the node itself and not this api?

2021-07-19 11:33 UTC, samuelsramko requested changes

2021-07-19 11:33 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +    async getBlock(@Param() hash: string) {
you are not validating Params in any request. Take a look how it is done on another connectors. Query and Path params must be validated the same way as request bodies

2021-07-20 09:35 UTC, samuelsramko requested changes
I dont see openapi.yaml file anywhere, which describes the API

2021-07-20 09:35 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +            return await generatePrivateKeyFromMnemonic(Currency.QTUM, true, body.mnemonic, body.index);
you have true here - shoud be await this.isTestnet()

2021-07-20 09:35 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +            return await generateAddressFromXPub(Currency.QTUM, true, xpub, Number(i));
you have true here - shoud be await this.isTestnet()

2021-07-20 09:35 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
> +            return await generateAddressFromPrivatekey(Currency.QTUM, true, key);
you have true here - shoud be await this.isTestnet()

2021-07-23 07:03 UTC, samuelsramko requested changes

2021-07-23 07:03 UTC, samuelsramko commented on qtum-connector/module/src/openapi.yaml
> +  - url: 'https://api-eu1.tatum.io'
you have a lot of errors here. Try to paste the content to https://editor.swagger.io/ and you will see.

2021-07-23 08:08 UTC, samuelsramko approved these changes

2021-07-23 08:08 UTC, merged