fixing errors for Qtum APIs
tatumio/tatum-blockchain-connector pull request #36
Opened 2021-07-24 11:34 UTC by Rachit-gaur

2021-07-24 17:05 UTC, samuelsramko requested changes

2021-07-24 17:05 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
>      async estimateFee(@Param() nblocks: number): Promise<any> {
This should be either @Param('nblocks') nblock: number, or @Param() params: {nblocks:number}

2021-07-24 17:05 UTC, samuelsramko commented on qtum-connector/module/src/QtumController.ts
>      async estimateFeePerByte(@Param() nblocks: number): Promise<any> {
This should be either @Param('nblocks') nblock: number, or @Param() params: {nblocks:number}

2021-07-25 06:56 UTC, Rachit-gaur commented on qtum-connector/module/src/QtumController.ts
>      async estimateFeePerByte(@Param() nblocks: number): Promise<any> {
changes made

2021-07-25 06:56 UTC, Rachit-gaur commented on qtum-connector/module/src/QtumController.ts
>      async estimateFee(@Param() nblocks: number): Promise<any> {
changes made

2021-07-26 12:57 UTC, samuelsramko approved these changes

2021-07-26 12:57 UTC, merged