Elrond connector
tatumio/tatum-blockchain-connector pull request #39
Opened 2021-08-18 14:12 UTC by isra67

2021-08-19 07:17 UTC, samuelsramko requested changes

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +      <li>Testnet - a chain used for testing purposes. Coins on the test chain have no value and can be obtained from
Devnet

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +  # /v3/egld/address/{xpub}/{index}:
we need to have mnemonic/index instead of xpub

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +  /v3/egld/web3/{xApiKey}/**:
remove this line and merge into previuos one. you can have 1 URL with multiple methods post/get/...

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/package.json
> +    "web3": "^1.3.5"
fix version to 1.4.0, because 1.5.0 is incompatible due to London HF.

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/src/EgldController.ts
> +  @Post('v3/egld/web3/:xApiKey/*')
remove v3/. we will push it to the Core due to simpler versioning.

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/src/EgldService.ts
> +        // const client = await this.getClient(await this.isTestnet());
remove this

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/src/EgldService.ts
> +    public async getTransactionCount(address: string) {
is get transaction by address available?

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/src/EgldService.ts
> +    public async web3Method(req: Request, key: string) {
I would not call it web3 method, because its not web3 compatible chain. I would go with "node" also in the URL and doc

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/src/EgldService.ts
> +    // public async sendCustomErc20Transaction(transferCustomErc20: TransferCustomErc20): Promise<TransactionHash | SignatureId> {
remove

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/src/EgldController.ts
> +  @Post('v3/egld/nft/wipe')
nfts should be only in the NFT abstraction, not here

2021-08-19 07:17 UTC, samuelsramko commented on egld-connector/module/src/EgldController.ts
> +  @Post('v3/egld/nft/wipe')
same applies to the ERC20 compatible tokens here

2021-08-19 07:56 UTC, isra67 commented on egld-connector/module/openapi.yaml
> +      <li>Testnet - a chain used for testing purposes. Coins on the test chain have no value and can be obtained from
ok

2021-08-19 07:56 UTC, isra67 commented on egld-connector/module/openapi.yaml
> +  # /v3/egld/address/{xpub}/{index}:
ok

2021-08-19 07:57 UTC, isra67 commented on egld-connector/module/openapi.yaml
> +  /v3/egld/web3/{xApiKey}/**:
I cant set multiple methods :-(

2021-08-19 07:57 UTC, isra67 commented on egld-connector/module/package.json
> +    "web3": "^1.3.5"
which package? I cant see 1.5.0

2021-08-19 08:04 UTC, isra67 commented on egld-connector/module/src/EgldController.ts
> +  @Post('v3/egld/web3/:xApiKey/*')
ok

2021-08-19 08:06 UTC, isra67 commented on egld-connector/module/src/EgldService.ts
> +        // const client = await this.getClient(await this.isTestnet());
ok

2021-08-19 08:07 UTC, isra67 commented on egld-connector/module/src/EgldService.ts
> +    public async getTransactionCount(address: string) {
yes
https://docs.elrond.com/sdk-and-tools/rest-api/addresses/#get-address-transactions

2021-08-19 08:30 UTC, isra67 commented on egld-connector/module/src/EgldService.ts
> +    public async web3Method(req: Request, key: string) {
ok

2021-08-19 09:33 UTC, samuelsramko commented on egld-connector/module/package.json
> +    "web3": "^1.3.5"
web3 should be fixed 1.4.0

2021-08-19 09:34 UTC, samuelsramko commented on egld-connector/module/src/EgldService.ts
> +    public async getTransactionCount(address: string) {
this one? https://docs.elrond.com/sdk-and-tools/rest-api/addresses/#get-address-transactions

2021-08-19 10:25 UTC, isra67 commented on egld-connector/module/src/EgldService.ts
> +    // public async sendCustomErc20Transaction(transferCustomErc20: TransferCustomErc20): Promise<TransactionHash | SignatureId> {
ok

2021-08-19 11:03 UTC, isra67 commented on egld-connector/module/src/EgldService.ts
> +    public async getTransactionCount(address: string) {
I use get-address-nonce to get nonce

2021-08-19 11:08 UTC, samuelsramko commented on egld-connector/module/src/EgldService.ts
> +    public async getTransactionCount(address: string) {
I was asking about get transaction by address, not get nonce. New method...

2021-08-19 12:58 UTC, isra67 commented on egld-connector/module/src/EgldService.ts
> +    public async getTransactionCount(address: string) {
> is get transaction by address available?

only for last 20 txs

2021-08-23 13:14 UTC, samuelsramko requested changes

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +                    example: erd1pnvwvgtm...
full address, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +      example: "/v3/egld/web3/{xApiKey}/transaction/cost"
not web3, but node

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +              example: {"version": 1,"chainId": "v1.0.141","nonce": 42,...}
fulll example, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +                description: Any valid response.
full response as you will receive for that specific request

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +      example: "/v3/egld/web3/{xApiKey}/network/config"
not web3, but node

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +            example: asdlkfjnqunalkwjf...
full response, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +            example: c9e9f6387c6...
full example, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +            example: "erd1pnvwvgtmf..."
full example, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +            example: "670aad15f2a2..."
full example, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +            example: "erd1pnvwvg..."
full example, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +            example: "erd1pnvwvgtmfg..."
full example, not ...

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +  /v3/egld/nft/{method}:
this will be reworked to meet our abstraction standard

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +    post:
this will be reworked to meet our abstraction standard

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +      operationId: EgldBlockchainSmartContract
different name of the opereation

2021-08-23 13:14 UTC, samuelsramko commented on egld-connector/module/openapi.yaml
> +          example: "eb7f5c60..."
replace all ... with real values everywhere

2021-08-23 14:03 UTC, merged