Add the new Cardano connector
tatumio/tatum-blockchain-connector pull request #4
Opened 2021-03-01 06:19 UTC by kk-hainq

2021-03-31 09:22 UTC, kk-hainq commented on cardano-connector/module/package.json
> +    "@tatumio/tatum": "~/Tatum/tatum-js",
Pending.

2021-03-31 10:24 UTC, tatumio requested changes

2021-03-31 10:24 UTC, tatumio commented on cardano-connector/module/openapi.yaml
> +        200:
Could you extract these values to a scheme object?

2021-03-31 10:24 UTC, tatumio commented on cardano-connector/module/openapi.yaml
> +  /v3/cardano/account/:address/transactions:
I would love pagination here, pageSize and offset kind of style. max page size is 50

2021-03-31 10:24 UTC, tatumio commented on cardano-connector/module/src/CardanoController.ts
> +  async getTransactionsByAccount(
Pagination - see https://tatum.io/apidoc#operation/getTransactionsByAccountId - query pagination section

2021-03-31 10:24 UTC, tatumio commented on cardano-connector/module/src/CardanoService.ts
> +    const fromAddress = CardanoWasm.Address.from_bech32(body.from);
this logic should be placed inside tatum-js lib

2021-04-04 02:25 UTC, kk-hainq commented on cardano-connector/module/openapi.yaml
> +        200:
Done and rebased.

2021-04-04 02:25 UTC, kk-hainq commented on cardano-connector/module/openapi.yaml
> +  /v3/cardano/account/:address/transactions:
Done and rebased.

2021-04-04 02:25 UTC, kk-hainq commented on cardano-connector/module/src/CardanoController.ts
> +  async getTransactionsByAccount(
Done and rebased.

2021-04-04 03:14 UTC, kk-hainq commented on cardano-connector/module/src/CardanoService.ts
> +    const fromAddress = CardanoWasm.Address.from_bech32(body.from);
Done and rebased.

2021-04-04 06:36 UTC, tatumio requested changes

2021-04-04 06:36 UTC, tatumio commented on cardano-connector/module/src/CardanoController.ts
> +    }
missing broadcast endpoint

2021-04-04 06:36 UTC, tatumio commented on cardano-connector/module/src/CardanoService.ts
> +          submitTransaction(transaction: "${transaction}") {
this should be separate method inside the service

2021-04-06 15:22 UTC, kk-hainq commented on cardano-connector/module/src/CardanoController.ts
> +    }
We've added and rebased.

2021-04-07 20:40 UTC, tatumio approved these changes
Waiting for correct tatumJS lib, otherwise OK

2021-04-07 21:06 UTC, Hathoriel reviewed
Really like your implementation, I have only one little comment.

2021-04-07 21:06 UTC, Hathoriel commented on cardano-connector/module/src/CardanoService.ts
> +import * as Tatum from '@tatumio/tatum';
I would recommend to import only functions that are really used in file. :-)

2021-04-08 17:30 UTC, kk-hainq commented on cardano-connector/module/src/CardanoService.ts
> +import * as Tatum from '@tatumio/tatum';
Done. Still need to wait for some `tatum-js` changes though.

2021-04-13 03:36 UTC, tatumio requested changes

2021-04-13 03:36 UTC, tatumio commented on cardano-connector/module/openapi.yaml
> +  /v3/cardano/block/:hash:
should be {hash} instead of :hash. Look at https://editor.swagger.io/ and fix all errors

2021-04-13 03:36 UTC, tatumio commented on cardano-connector/module/openapi.yaml
> +  /v3/cardano/wallet/priv:
missing tag parameter

2021-04-13 03:36 UTC, tatumio commented on cardano-connector/module/src/CardanoError.ts
> +  constructor(message: string, errorCode: string, statusCode = 500) {
Default status code should be 403

2021-04-13 06:58 UTC, linhdangkk commented on cardano-connector/module/openapi.yaml
> +  /v3/cardano/block/:hash:
Done

2021-04-13 06:58 UTC, linhdangkk commented on cardano-connector/module/openapi.yaml
> +  /v3/cardano/wallet/priv:
Added

2021-04-13 06:58 UTC, linhdangkk commented on cardano-connector/module/src/CardanoError.ts
> +  constructor(message: string, errorCode: string, statusCode = 500) {
Fixed

2021-04-13 11:14 UTC, merged