Algo connector
tatumio/tatum-blockchain-connector pull request #52
Opened 2021-09-22 15:35 UTC by JeyDev310

2021-09-23 14:24 UTC, samuelsramko requested changes

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +                - $ref: "#/components/schemas/TransferAlgrorandBlockchain"
There should be 2 types of schemes - one for private key and another one for KMS

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +              schema: type: object
response should not be type: object, but txId or signatureId from KMS. take a look to other endpoints

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +      parameters:
we need to add pagination here as well

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +  /v3/algorand/transaction:
missing get block operation

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoController.ts
> +  public async getPayTransactions(@Param() {from, to}: PathFromTo) {
add pagination here

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoController.ts
> +  public async getInfo() {
missign openapi

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +    return this.broadcast(await prepareAlgoSignedTransaction(await this.isTestnet(), tx, (await this.getNodesUrl())[0]));
you should use broadcastOrStoreKMSTransaction

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +    return (await (await this.getClient()).getTransactionParams().do()).firstRound;
extract await this getClient to variable fro better readability

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +      throw Error("Failed Algo Transaction Signing");
throw AlgoError

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +        throw e;
throw AlgoError

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +      throw e;
throw AlgoError

2021-09-23 14:24 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +    }).then(result => {
change to async/await

2021-09-24 13:11 UTC, samuelsramko requested changes

2021-09-24 13:11 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +        - description: "page size for pagenation"
type - pagination

2021-09-24 13:11 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +                $ref: "#/components/schemas/AlgorandTxsWithPagenation"
I dont see reference to this scheme. We need to have a description for each scheme you are referring to.

2021-09-24 13:11 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +                $ref: "#/components/schemas/AlgorandTx"
I dont see reference to this scheme. We need to have a description for each scheme you are referring to.

2021-09-24 13:11 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +                - $ref: "#/components/schemas/TransferAlgorandBlockchain"
I dont see reference to this scheme. We need to have a description for each scheme you are referring to.

2021-09-24 13:11 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +                $ref: "#/components/schemas/AlgoBlock"
I dont see reference to this scheme. We need to have a description for each scheme you are referring to.

2021-09-24 13:11 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +    return this.broadcastOrStoreKMSTransaction(await prepareAlgoSignedTransaction(await this.isTestnet(), tx, (await this.getNodesUrl())[0]));
you are passing the params wrong, in my opinion it should be like this

```
const txData = await prepareAlgoSignedTransaction(await this.isTestnet(), tx, (await this.getNodesUrl())[0]);
returnthis.broadcastOrStoreKMSTransaction({transactionData: txData, signatureId: tx.signatureId, index: tx.index})
```

2021-09-24 14:29 UTC, JeyDev310 commented on algo-connector/module/src/AlgoService.ts
> +    return this.broadcastOrStoreKMSTransaction(await prepareAlgoSignedTransaction(await this.isTestnet(), tx, (await this.getNodesUrl())[0]));
ah, right.

2021-09-27 08:26 UTC, samuelsramko requested changes

2021-09-27 08:26 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +    X-Api-Key:
this doesnt have to be here, it will be obtained from master openAPI from the core-api.

2021-09-27 08:26 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +    Wallet:
this doesnt have to be here, it will be obtained from master openAPI from the core-api.

2021-09-27 08:26 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +      properties:
missing required fields

2021-09-27 08:26 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> -                - $ref: "#/components/schemas/TransferAlgorandBlockchainKMS"
this should not be removed, btu present

2021-09-27 11:34 UTC, samuelsramko requested changes

2021-09-27 11:34 UTC, samuelsramko commented on algo-connector/example/src/AlgoService.ts
> +    const baseurl = (await this.isTestnet()) ? 'https://testnet-algorand.api.purestake.io/idx2' : 'https://algorand.api.purestake.io/idx2';
obtain from the abstract method as other URL methods pls

2021-09-27 13:56 UTC, samuelsramko requested changes

2021-09-27 13:56 UTC, samuelsramko commented on algo-connector/module/openapi.yaml
> +  /v3/algorand/wallet:
missing broadcast method

2021-09-27 13:56 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +  public async getPayTransactions(from: string, to: string, limit?:string, next?: string) {
add optional testnet parameter here. From the core-api scanner logic, you will call this method for mainnet or testnet simultaneously, so if parameter is present, it will be used, otherwise default isTestnet() from getNodesUrl().

2021-09-27 13:56 UTC, samuelsramko commented on algo-connector/module/src/AlgoService.ts
> +  public async getPayTransactions(from: string, to: string, limit?:string, next?: string) {
Take a look here - https://github.com/tatumio/tatum-blockchain-connector/blob/master/celo-connector/module/src/CeloService.ts#L54

2021-09-27 14:56 UTC, samuelsramko approved these changes

2021-09-27 14:58 UTC, merged