ERC 20 connector
tatumio/tatum-blockchain-connector pull request #9
Opened 2021-05-06 08:50 UTC by isra67

2021-05-06 09:49 UTC, tatumio requested changes

2021-05-06 09:49 UTC, tatumio commented on erc20-connector/example/src/app.controller.ts
> +export class AppController extends NftController {
should not be NftController

2021-05-06 09:49 UTC, tatumio commented on erc20-connector/example/src/app.service.ts
> +export class AppService extends NftService {
should not be NftService

2021-05-06 09:49 UTC, tatumio commented on erc20-connector/module/package.json
> +    "@tatumio/tatum": "file:../../../tatum-js",
move this to peerDependencies and install locally to devDependencies. Using this, tatum-js won't be included inside the target package

2021-05-06 09:49 UTC, tatumio commented on erc20-connector/module/src/Erc20Service.ts
> +      return null
throw otherwise

2021-05-06 09:49 UTC, tatumio commented on erc20-connector/module/src/Erc20Service.ts
> +            return {signatureId: await this.storeKMSTransaction(txData, chain, [body.signatureId], body['index'] || 0)};
body.index or undefined, not default 0. must be undefined if not present

2021-05-06 09:49 UTC, tatumio commented on erc20-connector/module/src/Erc20Service.ts
> +            return {signatureId: await this.storeKMSTransaction(txData, chain, [body.signatureId], body['index'] || 0)};
not default 0

2021-05-06 09:49 UTC, tatumio commented on erc20-connector/module/src/Erc20Service.ts
> +            return {signatureId: await this.storeKMSTransaction(txData, chain, [body.signatureId], body['index'] || 0)};
not default 0

2021-05-06 10:56 UTC, isra67 commented on erc20-connector/example/src/app.controller.ts
> +export class AppController extends NftController {
ok

2021-05-06 10:56 UTC, isra67 commented on erc20-connector/example/src/app.service.ts
> +export class AppService extends NftService {
ok

2021-05-06 10:57 UTC, isra67 commented on erc20-connector/module/src/Erc20Service.ts
> +      return null
ok

2021-05-06 10:57 UTC, isra67 commented on erc20-connector/module/src/Erc20Service.ts
> +            return {signatureId: await this.storeKMSTransaction(txData, chain, [body.signatureId], body['index'] || 0)};
ok

2021-05-06 10:57 UTC, isra67 commented on erc20-connector/module/src/Erc20Service.ts
> +            return {signatureId: await this.storeKMSTransaction(txData, chain, [body.signatureId], body['index'] || 0)};
ok

2021-05-06 10:57 UTC, isra67 commented on erc20-connector/module/src/Erc20Service.ts
> +            return {signatureId: await this.storeKMSTransaction(txData, chain, [body.signatureId], body['index'] || 0)};
ok

2021-05-06 11:54 UTC, isra67 commented on erc20-connector/module/package.json
> +    "@tatumio/tatum": "file:../../../tatum-js",
ok

2021-05-10 07:11 UTC, tatumio requested changes

2021-05-10 07:11 UTC, tatumio commented on erc20-connector/module/src/Erc20Service.ts
> +    protected broadcast(chain: Currency, txData: string, signatureId?: string) {
broadcast should be abstract and implemented inside core.

2021-05-10 07:11 UTC, tatumio commented on erc20-connector/module/src/Erc20Service.ts
> +            return {signatureId: await this.storeKMSTransaction(txData, chain, [body.signatureId], body['index'])};
I dont like body['index'], its old accessing. use body.index everywhere

2021-05-10 07:31 UTC, tatumio approved these changes

2021-05-10 07:32 UTC, merged